### ISSUE TITLE
[종만북] 문자열

### ISSUE THREAD

**Issue by fpdjsns** [fpdjsns/Algorithm-study#3]
**범위** : 20(문자열)
**기간** : 2020/02/02 ~ 2020/02/08

---
**문제** 
20.3 [제하의 금고](https://algospot.com/judge/problem/read/JAEHASAFE) (문제 ID: JAEHASAFE, 난이도: 중)
20.6 [말버릇](https://algospot.com/judge/problem/read/HABIT) (문제 ID: HABIT, 난이도: 중)

**Comment by vinus322** [comment]
문자열 어렵네요....

**Comment by vinus322** [comment]
KMP 알고리즘과 접미사 배열 내용 정리가 필요할 듯 합니다.

**Comment by vinus322** [comment]
모이는 날에 한번 정리하여 서로 설명하는 시간이 있음 좋겠습니다.
